env:
  global:
  - CLIENT_ADDRESS_HIDDEN=http://localhost:3000
  - CLIENT_ID_HIDDEN=test_id
  - CLIENT_SECRET_HIDDEN=test_secret
language: java
jdk: oraclejdk8
install: true
script:
- gradle assemble
#- gradle test
#before_cache:
#- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#  - "$HOME/.gradle/caches/"
#  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  on:
    all_branches: true
    repo: AdamGapinski/common-interests-network
  api_key:
    secure: "xbdAz8xYSwB1OILI4rtSfNfBlr5Rj0/Usdfr9c9VFy/FovHJzh7tbXepzqjYNHgEc03jSr1DpbkTfzvJxbVBy3WJxDXYXsYinien7SnlvFwEpNMZ/AQybSQzNR3cSIfTM1dmK1Jvo0TPXQ7bukPv9o8z0dX2jUsb0IpfR9BLB1KT3+vsZJ6fMbpFkMEZSVsKMoJGiOKNwYrqwWpg/2Hc5kFjVU1Nd+rAcTvBMOHxfG9lUZysJHZoBi95eO/+gFkMdlJdFaywsYk3k7KdfjE6rSgNxzX40WwXScnqiEUH0nDhuCiuFXtrgiBg7WSIoIo6gx9wfzqOi3ENtYrBWnmqABTHzB46Ubgx8pawM5H39xvTbew4VmByWeq0dyrVnzjrrEqVBUFXLjoq89oX/4UzBZOQorswm4M6rVvCWEfvRZ6LoNJ9dX1+yiTS5ZGilQof2cF3ua9j/0hj49Un2srF0PPujiy1qf73KV93XxmS3APb9d0k6xxoVeTSDENcnn74Pw4nvCiYBod1zbyZ1tbug7D2zzJzBSmls77r0FRIp1JxPaQoNc5xTOO0bIsIv4qsHfxwzWbLEsv4Cw/FTSZ5xSRPu78sm0HqJTMke0qFLojHIEXCp2xdOgWyWo+V6w0ZCXKhzPHBiDBB9+D27XlkNnLSjAmHt3T/5+f7QB6hSbE="
  app: common-interests-network
