env:
  global:
  - CLIENT_ADDRESS_HIDDEN=http://localhost:3000
  - CLIENT_ID_HIDDEN=test_id
  - CLIENT_SECRET_HIDDEN=test_secret
language: java
jdk: oraclejdk8
install: true
script:
- gradle assemble
- gradle test
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  on:
    all_branches: true
    repo: AdamGapinski/common-interests-network
  api_key:
    secure: BghiQWRJcFbM/5t1dZB8MztLxEHWBVgSzd5YzpXYRVH+3GrvKk6VVtVoNqeoxhbcfuFwW1hblSIUeA+PS7YuBl9WUGXXW5Kt7atUOCse2/x6F3dwdI6SD1uwDtsiuNDyLgrImfOQZapUm0eoD/FyrEdf+YGRYgEV9qUP+/oq6hZ0KA7VuXvXAbyrlDAcSqOF65Cp8SQnMQIuUukmVcAKtsYsTIMnlrks3bTt9hd+HqCuDpia+OFeLhnMEJOYSm3hZh1MsQzeRWFBZTlt5BPkEyUFjiHWWImXqF1XxWHRasHR2Vsd/olYNJlUyxAozzE+BCPBFg6hSK6afG8YmSEyegdjXuIt8EVRrZ6htorBEh8MlOZR9PI+6p/P+ToFV1cuCc5IutwSTHsvpyJwKOU4Jh6x3DBh9wt8Xe8hFdTczc4TiXDcK/Yd8yHczbKy+RE1ecG+NwB00RrmBp2786X4VnWF+clUA+ZAczHofjmP4bGrVQdLIiOsG3UM4Y+ytMU6vZvxUSEKvayY3msRXANVcJHeWGInk+SMHdgs30+IEjK6Kdh+Ca1YeXKIebQFORHYJs2BQrEOrEB4ji4BgSobntWILLCowqI4c8+G7MpkO+3jtPsDVE4CPMfbssSflnVqXCYn5j3rAl6ScSngYriP9PNpEE9iyUl3LceyLIco/3k=
  app: common-interests-network
